    TG: oh no
    TG: no dude
    TG: you sassed me up
    TG: we are in THE SHIT now
    TG: together
    TG: for the long haul

    AT: i,
    AT: wHAT,

    TG: we're motherfuckin entrenched in this bitch
    TG: you and me
    TG: welcome to nam
    TG: now grab my hand and shimmy your soggy ass off that muddy bank before
        charlie gets the fuckin drop

    AT: uHHH, wHO,
    AT: wHO'S CHARLIE,

    TG: hes the guy whos gonna read our vows
    TG: im feeling pretty friggin MATRIMONIAL all a sudden
    TG: take a look down by your foot see that little bottle
    TG: stomp on that shit like its on fire
    TG: noisy ethnic dudes are flipping the fuck out and waving us around on chairs
        til someone gets hurt
    TG: im your 300 pound matronly freight-train
    TG: and my gaping furnace is hungry for coal so get goddamn shoveling

    AT: oH MY GOD,

    TG: bro look in my eyes
    TG: that twinkle
    TG: that be DEVOTION you herniated pro wrestlers sweaty purple taint
    TG: sparklin like a visit from your fairy fuckin godmother
    TG: shit be PURE AND TRUE
    TG: thats what you see
    TG: a kaleidoscopic supernova of all your hopes and dreams all swishin together
    TG: radially effevescing arms of more little boy peckers than you can imagine
    TG: turning out insane corkscrew haymakers of a billion dancing vienna sausages
        strong
    TG: this is how we do this
    TG: this shits more real than kraft mayo

-- "Dave: Answer." via http://www.mspaintadventures.com/?s=6&p=002999
